name: Translate & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm install
      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli
      - name: Sync Translations with Crowdin
        run: npm run crowdin:sync
      - name: Deploy to GH Pages
        run: GIT_USER=rekuenkdr USE_SSH=true npm run deploy